version: "3.9"

services:
  dbPostgres:
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_volume:
